#!/bin/env sh
brew install --cask visual-studio-code webstorm docker warp github lens font-fira-code
mas install 497799835 	# Xcode
xcode-select --install
brew install git docker-compose node
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
brew install romkatv/powerlevel10k/powerlevel10k
echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc